class CreateEquipments < ActiveRecord::Migration
  def change
    create_table :equipments do |t|
      t.string :head
      t.string :head_icon
      t.string :head_quality
      t.integer :head_itemlvl
      t.integer :head_stat
      t.integer :head_stat_amount
      t.string :neck
      t.string :neck_icon
      t.string :neck_quality
      t.integer :neck_itemlvl
      t.integer :neck_stat
      t.integer :neck_stat_amount
      t.string :shoulder
      t.string :shoulder_icon
      t.string :shoulder_quality
      t.integer :shoulder_itemlvl
      t.integer :shoulder_stat
      t.integer :shoulder_stat_amount
      t.string :back
      t.string :back_icon
      t.string :back_quality
      t.integer :back_itemlvl
      t.integer :back_stat
      t.integer :back_stat_amount
      t.string :chest
      t.string :chest_icon
      t.string :chest_quality
      t.integer :chest_itemlvl
      t.integer :chest_stat
      t.integer :chest_stat_amount
      t.string :wrist
      t.string :wrist_icon
      t.string :wrist_quality
      t.integer :wrist_itemlvl
      t.integer :wrist_stat
      t.integer :wrist_stat_amount
      t.string :hands
      t.string :hands_icon
      t.string :hands_quality
      t.integer :hands_itemlvl
      t.integer :hands_stat
      t.integer :hands_stat_amount
      t.string :waist
      t.string :waist_icon
      t.string :waist_quality
      t.integer :waist_itemlvl
      t.integer :waist_stat
      t.integer :waist_stat_amount
      t.string :legs
      t.string :legs_icon
      t.string :legs_quality
      t.integer :legs_itemlvl
      t.integer :legs_stat
      t.integer :legs_stat_amount
      t.string :feet
      t.string :feet_icon
      t.string :feet_quality
      t.integer :feet_itemlvl
      t.integer :feet_stat
      t.integer :feet_stat_amount
      t.string :finger_1
      t.string :finger_1_icon
      t.string :finger_1_quality
      t.integer :finger_1_itemlvl
      t.integer :finger_1_stat
      t.integer :finger_1_stat_amount
      t.string :finger_2
      t.string :finger_2_icon
      t.string :finger_2_quality
      t.integer :finger_2_itemlvl
      t.integer :finger_2_stat
      t.integer :finger_2_stat_amount
      t.string :trinket_1
      t.string :trinket_1_icon
      t.string :trinket_1_quality
      t.integer :trinket_itemlvl
      t.integer :trinket_1_stat
      t.integer :trinket_1_stat_amount
      t.string :trinket_2
      t.string :trinket_2_icon
      t.string :trinket_2_quality
      t.integer :trinket_2_itemlvl
      t.integer :trinket_2_stat
      t.integer :trinket_2_stat_amount
      t.string :main_hand
      t.string :main_hand_icon
      t.string :main_hand_quality
      t.integer :main_hand_itemlvl
      t.integer :main_hand_stat
      t.integer :main_hand_stat_amount
      t.string :off_hand
      t.string :off_hand_icon
      t.string :off_hand_quality
      t.integer :off_hand_itemlvl
      t.integer :off_hand_stat
      t.integer :off_hand_stat_amount

      t.timestamps
    end
  end
end
